### ISSUE TITLE
Touch Button C16, C17 are not working

### ISSUE THREAD

**Issue by paschkel** [MKleinSB/pxt-calliope-buttons#2]
Hi Michael,
I am using your touch extension with Calliope mini. Touch button P1, P2 are working well, however, I am not able to get C16, C17 running. Not sure what I am doing wrong. can you help me? I assume you tested all four buttons.
Thanks 
Pascal

**Comment by MKleinSB** [comment]
Danke für den Hinweis, da muss ich mal schauen was ich da ändern muss.

**Comment by MKleinSB** [comment]
Should be fixed now (I hope)
